config/routes.rb
Start::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :activities, only: :show do
    post :apply, on: :member
  end
  resources :people, only: :show

  devise_for :volunteers, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :volunteer do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  authenticated :volunteer do
    get 'me', to: 'volunteers#me'
    
  end
  root :to => 'welcome#index'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :person, class_name: Person
  belongs_to :volunteer
  belongs_to :category
  attr_accessible :name, :deadline, :description, :state, :person_id, :category_id, :state

  state_machine :state, :initial => :open do
    event :apply do
      transition :open => :inprogress
    end

    event :finish do
      transition any => :done
    end

  end 

  rails_admin do
    configure :name, :string
    configure :person, :belongs_to_association
    configure :description, :text
    configure :deadline, :date
    configure :category, :belongs_to_association
    configure :volunteer do; read_only true end

    configure :state, :enum do
      enum do
        %w[open inprogress done]
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :icon, :name
  has_many :activities
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :activities, inverse_of: :person
  attr_accessible :address, :name, :dob, :phone
  geocoded_by :address   # can also be an IP address
  after_validation :geocode  

  rails_admin do
    configure :dob, :date
  end
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise  :trackable, :omniauthable
  has_many :activities
  has_many :people, through: :activities

  # attr_accessible :title, :body
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  def apply
    raise unless current_volunteer
    @activity = Activity.where(state: :open).find params[:id]
    @activity.volunteer = current_volunteer
    if @activity.apply
      flash[:info]= 'You are applied for an activity'
      redirect_to '/me'
    else
      flash[:error]="Unable to apply. Sorry"
      redirect_to action: :show
    end

  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/omniauth_callbacks_controller.rb
#encoding: utf-8
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def failure
    flash[:alert] = "Невдалось авторизуватись через facebook"

    if request.env['omniauth.params']['activity'].present?
      redirect_to ::Activity.find request.env['omniauth.params']['activity']
    else
      redirect_to :root 
    end
  end

  def facebook
    @volunteer = Volunteer.find_or_create_by_uid request.env["omniauth.auth"]["uid"] do |v|
      %w(email image name location).each do |f|
        v.send f+?=, request.env["omniauth.auth"]["info"][f]
      end
    end

    if @volunteer.persisted?
      if request.env['omniauth.params']['activity'].present?
        sign_in @volunteer
        redirect_to ::Activity.find request.env['omniauth.params']['activity']
      else
        sign_in_and_redirect @volunteer, :event => :authentication #this will throw if @volunteer is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      end
    else
      #would not get here
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_volunteer_registration_url
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def me
    @activities = Activity.find_all_by_volunteer_id current_volunteer.id
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @json = "document.points = "
    @json += Person.includes(:activities=>:category).map do |p|
      {
        latitude:   p.latitude,
        longitude:  p.longitude,
        activity: {
          id: p.activities.last.try(:id),
          name: p.activities.last.try(:name),
          deadline: p.activities.last.try(:deadline),
          description: p.activities.last.try(:description),
          icon: p.activities.last.try(:category).try(:icon)
        }
      }
    end.to_json
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/activities/_form.html.haml
= simple_form_for @activity, :html => { :class => 'form-horizontal' } do |f|
  = f.input :category
  = f.input :deadline
  = f.input :description
  = f.input :state
  = f.input :person_id
  = f.input :volunteer_id
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), activities_path, :class => 'btn'

app/views/activities/edit.html.haml
- model_class = Activity
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/activities/index.html.haml
- model_class = Activity
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:category)
      %th= model_class.human_attribute_name(:deadline)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:state)
      %th= model_class.human_attribute_name(:person_id)
      %th= model_class.human_attribute_name(:volunteer_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @activities.each do |activity|
      %tr
        %td= link_to activity.id, activity_path(activity)
        %td= activity.category
        %td= activity.deadline
        %td= activity.description
        %td= activity.state
        %td= activity.person_id
        %td= activity.volunteer_id
        %td=l activity.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_activity_path(activity), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), activity_path(activity), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_activity_path, :class => 'btn btn-primary'

app/views/activities/new.html.haml
- model_class = Activity
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/activities/show.html.haml
.container#activity-show
  .well.decor.span6.offset3
    .row
      .span4.relative
        %span.icon-heart.icon-heart-small
        .category.shop
          Deadline:
          =@activity.deadline
        %h1.darkgray=@activity.name
        %p.status{class: @activity.state}
          Status:
          =@activity.state
        %p.lightgray
          =@activity.description
      - if volunteer_signed_in? and @activity.volunteer = current_volunteer
        .span2.ptm.border-left
          %h2.darkgray=@activity.person.try :name
          %p.lightgray 
            =@activity.person.try(:address)
            %br
            =@activity.person.try(:phone)
    .row
      .span6.ptm
        - unless volunteer_signed_in?
          = link_to volunteer_omniauth_authorize_path('facebook', activity: @activity.id), class: ['btn','btn-info', 'brand'], id: 'fb-login' do
            %i.icon-facebook-sign
            Login to apply
        - else
          - disabled = @activity.open? ? nil : 'disabled inactive'
          = button_to 'Apply', apply_activity_path(@activity), method: :post, class: [:btn, 'btn-success', disabled], id: 'apply-btn', :confirm => ("Are you sure?" unless disabled)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Help for Free – Choose your time and place to help." %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner" style="background:#3b3b3b;">
        <div class="container-fluid">
          <%=link_to :root do %>
            <div class="logotype pull-left"><img src="/logotype.png"></div>
          <% end %>
          <% if volunteer_signed_in? %>
            <div class="container pull-right">
              <span class='visible-phone pull-right'>
                <%= link_to destroy_user_session_path, class:[:btn, :'btn-large', :'btn-inverse'] do%>
                  <i class="icon-external-link muted"></i>
                <% end %>
              </span>
              <div class='pull-left' id='ava-block'>
                <%= link_to me_path, class: [:'pull-right', :thumbnail, :me] do %>
                  <%= image_tag current_volunteer.image%>
                <%-end%>
              </div>
              <span class='hidden-phone'>
                <div class="pull-left row">
                  <%= link_to current_volunteer.try(:name), me_path, class: ['skyblue'] %>
                  <%= link_to destroy_user_session_path, class:[:btn, :'btn-mini', :'btn-inverse'] do%>
                    <i class="icon-external-link muted"></i>
                  <% end %>
                </div>
                <span class='pull-left row' id='achievements'>
                  <div class="badge badge-success">2 doing</div>
                  <div class="badge badge-info">23 done</div>
              </span>
              </span>
            </div><!--/.nav-collapse -->
          <%else%>

            <%= link_to volunteer_omniauth_authorize_path('facebook'), class: ['btn','btn-info', 'pull-right'], id: 'fb-login' do%>
              <i class="icon-facebook-sign"></i>Login
            <%-end%>
          <%-end%>
        </div>
      </div>
    </div>
    <%= bootstrap_flash %>
    <%= yield %>
    <hr>
    <footer>
      <p style="padding-left:30px;">&copy; Help4Free 2013</p>
    </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/people/_form.html.haml
= simple_form_for @person, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :address
  = f.input :dob
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), people_path, :class => 'btn'

app/views/people/edit.html.haml
- model_class = Person
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/people/index.html.haml
- model_class = Person
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:address)
      %th= model_class.human_attribute_name(:dob)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @people.each do |person|
      %tr
        %td= link_to person.id, person_path(person)
        %td= person.name
        %td= person.address
        %td= person.dob
        %td=l person.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_person_path(person), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), person_path(person), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_person_path, :class => 'btn btn-primary'

app/views/people/new.html.haml
- model_class = Person
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/people/show.html.haml
- model_class = Person
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @person.name
%p
  %strong= model_class.human_attribute_name(:address) + ':'
  %br
  = @person.address
%p
  %strong= model_class.human_attribute_name(:dob) + ':'
  %br
  = @person.dob

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), people_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_person_path(@person), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), person_path(@person), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/volunteers/me.haml
.container#activity-show
  .well.decor.span6.offset3
    .row.plxm
      %h1.darkgray
        %span.prs
          =image_tag current_volunteer.image
        =current_volunteer.name
        %span.pl
          .badge.badge-success 2 doing
          .badge.badge-info 23 done
    %hr
    .row.plxm
      -if current_volunteer.activities.empty?
        %h4
          You have not applied for any task yet.
          =link_to 'Go', root_path, class: :supasupablue
          and choose one now!
      -else
        -current_volunteer.activities.each do |a|
          %span.lightgray= a.updated_at.to_date
          = link_to activity_path(a) do
            %p.darkgray.pbs= a.name

app/views/welcome/index.haml
%script(type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU")
=javascript_tag @json
.row.plm.pbs
  #moto.span5
    %h2.supablue We connect people
    %h2.supablue with desire to help
    %h2.supablue and those who need it.
  .span6.offset1.ptm
    %img(src='/intro.png')
#map
.row-fluid.ptm
  .span4.pam
    %h4 No more loneliness
    %blockquote
      "The time I feel most lonely is after six o’clock at night, but when I’ve been out to a Contact tea, then I don’t feel lonely at all, just fresh memories of a lovely afternoon out with friends. It’s good getting out and meeting people and it’s fun for us to get together. It has made such a difference to my life" 
      %small Clare

  .span4.pam
    %h4 Bringing joy to older people
    %blockquote
      "I have had many good experiences both volunteering and visiting my neighbor Lucy. My volunteer experience has shown me that I can bring joy to older people. Everyone will have to face having parents and grandparents growing older and becoming dependent on their children. Dealing with this situation has made me a stronger and more caring person."
      %small Peter

  .span4.pam
    %h4 Good progress
    %blockquote
      "Having to stop working two and half years ago because of my illness was really difficult for me. I loved working and had worked very hard at not to have to give up - working part-time and then as a temp. As a volunteer I feel as if I am working again! I have progressed in a way that 3 years ago I would have never thought possible. I don't think it's an exaggeration to say that without the volunteering I might not even be here today." 
      %small Robert